#!/bin/sh
export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

print_help()
{
  echo ""
  echo "Použití: tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]]"
  echo ""
  echo "PŘÍKAZ může být jeden z:"
  echo "  list-tick   - výpis seznamu vyskytujících se burzovních symbolů, tzv. \"tickerů\""
  echo "  profit      - výpis celkového zisku z uzavřených pozic"
  echo "  pos         - výpis hodnot aktuálně držených pozic, seřazených sestupně dle hodnoty"
  echo "  last-price  - výpis poslední známé ceny pro každý ticker"
  echo "  hist-ord    - výpis histogramu počtu transakcí dle tickeru"
  echo ""
  echo "FILTR může být kombinace následujících:" 
  echo "  -a DATETIME - jsou uvažovány pouze hodnoty PO tomto datu(bez tohoto data)"
  echo "              - DATETIME je ve formátu YYYY-MM-DD HH:MM:SS"
  echo "  -b DATETIME - jsou uvažovány pouze záznamy PŘED tímto datem(bez tohoto data)"
  echo "  -t TICKER   - jsou uvažovány pouze záznamy odpovídající danému tickeru."
  echo "              - při více výskytech přepínače se bere množina všech uvedených tickerů"
  echo "  -w WIDTH    - u výpisu grafů nastavuje jejich šířku, tedy délku nejdelšího řádku na WIDTH"
  echo "              - WIDTH musí být kladné celé číslo. Více výskytů přepínače je chybné spuštění"
  echo ""
}

COMMAND=""
FILTERS=""
GZFILES=""
OUTPUT=""
FILES=""
FIRST_COMMAND="TRUE"
READ_INPUT=""
WIDTH=""
FIRST_WIDTH="TRUE"

while [ "$#" -gt 0 ]; do
  case "$1" in
    -h | --help)
      print_help
      exit 0
      ;;
    list-tick | profit | pos | last-price | hist-ord | graph-pos)
      if [ "$FIRST_COMMAND" = "FALSE" ]; then
        echo "Lze zadat pouze jeden příkaz!"
        exit 1
      fi
      COMMAND="$1"
      FIRST_COMMAND="FALSE"
      shift
      ;;
    -a | -b | -t | -w)
      FILTERS="$FILTERS $1 $2"
      shift
      shift
      ;;
    *.log.gz)
      if [ "$READ_INPUT" = "" ]; then
        READ_INPUT="gunzip -c $1"
      else
        READ_INPUT="$READ_INPUT | gunzip -c $1"
      fi
      if [ "$GZFILES" != "" ]; then
        GZFILES="$GZILES "
      fi
      GZFILES="$GZFILES$1"
      shift
      ;;
    *.log)
      if [ "$READ_INPUT" = "" ]; then
        READ_INPUT="cat $1"
      else
        READ_INPUT="$READ_INPUT | cat - $1"
      fi
      if [ "$FILES" != "" ];then
        FILES="$FILES "
      fi
      FILES="$FILES$1"
      shift
      ;;
    *)
      echo "neznámý argument \"$1\""
      exit 1
      ;;
  esac
done

if [ "$GZFILES" != "" ]; then
  for GZFILE in $GZFILES; do
    if [ ! -r $GZFILE ]; then
      echo "soubor $GZFILE nenalezen"
      exit 1
    fi
  done
fi

if [ "$FILES" != "" ]; then
  for FILE in $FILES; do
    if [ -r $FILE ]; then
      continue
    else
      echo "Soubor $FILE nenalezen"
      exit 1
    fi
  done
fi

if [ "$FILES" = "" ] && [ "$GZFILES" = "" ]; then
  if test -t 0; then
    echo "Nebyl zadán žádný soubor"
    exit 1
  fi
  READ_INPUT=""
fi
EDITED="$READ_INPUT"
TICKERS_FIND=""
I=1
DATE_AFTER=""
DATE_BEFORE=""

for FILTER in $FILTERS; do
I=$((I+1))
 case $FILTER in
  -t)
    VALUE=$(echo $FILTERS | cut -d ' ' -f $I)
    if [ "$TICKERS_FIND" != "" ]; then
      TICKERS_FIND="$TICKERS_FIND || \$2 == \"$VALUE\""
    else
      TICKERS_FIND="\$2 == \"$VALUE\""
    fi
    ;;
  -a)
    DATE_AFTER=$(echo $FILTERS | cut -d ' ' -f $I,$(($I+1)))
    ;;
  -b)
    DATE_BEFORE=$(echo $FILTERS | cut -d ' ' -f $I,$(($I+1)))
    ;;
  -w)
    if [ "$FIRST_WIDTH" = "FALSE" ]; then
      echo "-w lze použít pouze jednou"
      exit 1
    fi
    WIDTH=$(echo $FILTERS | cut -d ' ' -f $I)
    FIRST_WIDTH="FALSE"
 esac
done

if [ "$TICKERS_FIND" != "" ]; then
  if [ "$EDITED" != "" ]; then
    EDITED="$EDITED |"
  fi
  EDITED="$EDITED awk -F\; '$TICKERS_FIND { print \$0 }'"
fi


if [ "$DATE_AFTER" != "" ]; then
  if [ "$EDITED" != "" ]; then
    EDITED="$EDITED |"
  fi
  EDITED="$EDITED awk -F\; -v DATE_AFTER='"$DATE_AFTER"' '{ if (\$1 > DATE_AFTER) print \$0}'"        
fi


if [ "$DATE_BEFORE" != "" ]; then
  if [ "$EDITED" != "" ]; then
    EDITED="$EDITED |"
  fi   
  EDITED="$EDITED awk -F\; -v DATE_BEFORE='"$DATE_BEFORE"' '{ if (\$1 < DATE_BEFORE) print \$0}'"
fi
case $COMMAND in
  list-tick)
    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi
    EDITED="$EDITED awk -F\; '{print \$2}' | sort -u"
    ;;
  profit)
    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi
    EDITED="$EDITED awk -vOFMT='%.2f' -F\; -v profit=0.00 '{ if (\$3 == \"buy\") { profit-=\$4*\$6 } else { profit+=\$4*\$6 }} END { print profit }'"
    ;;
  pos)
   LONGEST_LINE=0
    LONGEST_LINE=$(eval "$EDITED" | sort -t\; -k2,2 -k1,1 -r | awk -F\; -v j="1" '{
    {ArrayTickers[NR]=$2}
    if(ArrayTickers[NR] != ArrayTickers[NR-1])
    {
      {LAST_PRICE[j]=$4}
      {j++}
    }
    if($3 == "sell")
    {       
      ArrayHolding[NR]-=$6
    }
    else
    {
      ArrayHolding[NR]+=$6
    }
    }
    END {{j=1} for(i=1;i<=NR+1;i++)
    {
      if(ArrayTickers[i] == ArrayTickers[i-1])
      {
        ArrayHolding[i]+=ArrayHolding[i-1]
      }
      else if (i == 1) {continue}
      else
      {
        {printf "%10s;%.2f\n", ArrayTickers[i-1], ArrayHolding[i-1]*LAST_PRICE[j]}
        {j++}
      }
}}' | awk -F\; -v longest="$LONGEST_LINE" '{ if (length($2)>longest) longest=length($2)} END {print longest}')

    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi 
    EDITED="$EDITED sort -t\; -k2,2 -k1,1 -r | awk -F\; -v j="1" -v longest="$LONGEST_LINE" '{
    {ArrayTickers[NR]=\$2}
    if(ArrayTickers[NR] != ArrayTickers[NR-1])
    {
      {LAST_PRICE[j]=\$4}
      {j++}
    }
    if(\$3 == \"sell\")
    {       
      ArrayHolding[NR]-=\$6
    }
    else
    {
      ArrayHolding[NR]+=\$6
    }
    }
    END {{j=1} for(i=1;i<=NR+1;i++)
    {
      if(ArrayTickers[i] == ArrayTickers[i-1])
      {
        ArrayHolding[i]+=ArrayHolding[i-1]
      }
      else if (i == 1) {continue}
      else
      {
        {printf \"%-10s: %*.2f\n\", ArrayTickers[i-1], longest, ArrayHolding[i-1]*LAST_PRICE[j]}
        {j++}
      }
}}'| sort -t\: -n -r -k2,2" 
    ;;
  last-price)
    LONGEST_LINE=$(eval "$EDITED" | sort -t\; -k2,2 -k1,1 -r | sort -t\; -k2,2 -u | awk -F\; -v longest=0 '{ if(length($4)>longest) { longest=length($4)}} END {print longest} ')
    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi
    EDITED="$EDITED sort -t\; -k2,2 -k1,1 -r | sort -t\; -k2,2 -u | awk -F\; -v longest="$LONGEST_LINE" '{if(length(\$4)>longest) { longest=length(\$4)} printf \"%-10s: %*s\n\",\$2,longest, \$4}'"
    ;;
  hist-ord)
    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi
    EDITED="$EDITED sort -t\; -k2,2 | awk -F \; -v WIDTH="$WIDTH" -v TMP=1 -v SUM=1 '{
    {TICKERS[NR]=\$2}
    if(TICKERS[NR]==TICKERS[NR-1]) { TMP++ }
    else if (NR==1) {}
    else
    { 
      if(TMP > MAX){ {MAX=TMP} {TMP = 1}}
      else {TMP=1}
    }
    }
    END{
    if (WIDTH == \"\") {WIDTH=MAX}
    for(i = 1; i <= NR+1; i++){        
      if(TICKERS[i] == TICKERS[i-1]) { SUM++ }
      else if (i==1) {continue}
      else
      {
        {DIVIDENT=MAX/WIDTH}
        {WRITE=int(SUM/DIVIDENT)} 
        {HASHTAGS=\"\"}
        for (j=0; j<WRITE; j++)
        {
          HASHTAGS=HASHTAGS \"#\"
        }
        {printf \"%-10s: %s\n\", TICKERS[i-1], HASHTAGS}
        {SUM=1}
      }
    }}'"
    ;;
    graph-pos)
    LONGEST=$(eval "$EDITED" | sort -t \; -k2,2 -k1,1 -r | awk -F\; -v j=1 'function abs(x){return ((x < 0.0) ? -x : x)}{
    {ArrayTickers[NR]=$2}
    if(ArrayTickers[NR] != ArrayTickers[NR-1])
    {
      {LAST_PRICE[j]=$4}
      {j++}
    }
    if($3=="sell") {ArrayHolding[NR]-=$6}
    else {ArrayHolding[NR]+=$6}}
    END {{j=1} for(i=1; i<=NR+1; i++){
      if (ArrayTickers[i]== ArrayTickers[i-1]) {ArrayHolding[i]+=ArrayHolding[i-1]}
      else if (i==1) {continue}
      else 
      {
        {ACT=ArrayHolding[i-1]*LAST_PRICE[j]}
        if ( abs(ACT) > abs(LONGEST) ) { LONGEST=ACT }
        {j++}
      }}
      printf "%.2f", LONGEST}')
    if [ "$EDITED" != "" ]; then
      EDITED="$EDITED |"
    fi
    EDITED="$EDITED sort -t\; -k2,2 -k1,1 -r | awk -F\; -v j="1" -v WIDTH="$WIDTH" -v LONGEST="$LONGEST" 'function abs(x){return ((x < 0.0) ? -x : x)} {
    {ArrayTickers[NR]=\$2}
    if(ArrayTickers[NR] != ArrayTickers[NR-1])
    {
      {LAST_PRICE[j]=\$4}
      {j++}
    }
    if(\$3 == \"sell\") {ArrayHolding[NR]-=\$6}
    else {ArrayHolding[NR]+=\$6}
    }
    END {
    {j=1}
    if(WIDTH==\"\") {WIDTH=LONGEST/1000}
    {DIVIDENT=abs(LONGEST/WIDTH)}
    for(i=1;i<=NR+1;i++)
    {
      {PRINTING=\"\"}
      if(ArrayTickers[i] == ArrayTickers[i-1]){ArrayHolding[i]+=ArrayHolding[i-1]}
      else if (i == 1) {continue}
      else
      {
          {ACT=ArrayHolding[i-1]*LAST_PRICE[j]}
          {WRITE=abs(ACT/DIVIDENT)}
          {WRITE=int(WRITE+0.00000000001)}
          {j++}
          if(ACT < 0){for (x=0; x<WRITE; x++){PRINTING=PRINTING \"!\"}}
          else{for (x=0; x<WRITE; x++){PRINTING=PRINTING \"#\"}} 
          { printf \"%-10s: %s\n\", ArrayTickers[i-1], PRINTING }
      }
}}'"
esac

if [ "$EDITED" != "" ]; then
  eval $EDITED 
else
 while read LINE; do
  echo $LINE
 done
fi
